### ISSUE TITLE
Problem with regular two degree

### ISSUE THREAD

**Issue by debbardet** [aymeric-spiga/dynamico-giant#3]
I can't run the model with 64 vertical levels because I have this error message : 

0335: > Error [CField::solveGridReference(void)] : In file '/scratch/cnt0027/lmd1167/dbardet/dynamico-giant/code/XIOS/src/node/field.cpp', line 1334 -> Invalid reference to domain 'regular_two_degree'.
0335:
0335: application called MPI_Abort(MPI_COMM_WORLD, -1) - process 335

Do you know what's happening ?

**Comment by debbardet** [comment]
I find the problem: I used a grid not defined in icosa.xml... It is enough to add these lines into icosa.xml: 
      <domain id="regular_two_degree" type="rectilinear" ni_glo="180" nj_glo="90" >
       <generate_rectilinear_domain />
       <interpolate_domain order="1"/>
     </domain>

**Comment by aymeric-spiga** [comment]
Interesting. You did solve the problem, but introduced a redundancy. Because there is a common declaration of domains between the physics and the dynamics: it is the file `domain_def.xml` which is then referenced in `icosa.xml`, see here https://github.com/aymeric-spiga/dynamico-giant/blob/6058e908dbd5f3499c4ec72adf1014b7e10a58d7/saturn/icosa.xml#L171

**Comment by aymeric-spiga** [comment]
I am going to change the reference to regular_two_degree which is not correct, and remove the lines that were commented. I should have removed those commented lines because it is confusing!

**Comment by debbardet** [comment]
Bonjour Aymeric, 

On peut faire un update depuis occigen avec git ? 

j'ai essayé git up mais visiblement ce n'est pas ça... 

A plus, 
Deborah 

De: "Aymeric SPIGA" <notifications@github.com> 
À: "aymeric-spiga/dynamico-giant" <dynamico-giant@noreply.github.com> 
Cc: "debbardet" <deborah.bardet@lmd.jussieu.fr>, "State change" <state_change@noreply.github.com> 
Envoyé: Jeudi 27 Septembre 2018 10:10:59 
Objet: Re: [aymeric-spiga/dynamico-giant] Problem with regular two degree (#3) 



Closed [ https://github.com/aymeric-spiga/dynamico-giant/issues/3 | #3 ] via [ https://github.com/aymeric-spiga/dynamico-giant/commit/a9635b3958f4ec3b44fcb65b3d126480cece6e50 | a9635b3 ] .
