### ISSUE TITLE
Weird warning in tpindex with 64 levels

### ISSUE THREAD

**Issue by ehouarn** [aymeric-spiga/dynamico-giant#9]
Running Saturn case with 64 levels, I get this weird warning from tpindex:
000:  tpindex: Caution! Pressure of upper levels lower than ref pressure for k-coef: 
000:  k-coeff fixed for upper levels
000:           PWL=  -3.11805930589871     
000:           PREF(1)=  -3.00000000000000     
But codes seems to run properly

**Comment by aymeric-spiga** [comment]
Does not seem to occur with 32-level simulations (tried with debug mode)

**Comment by aymeric-spiga** [comment]
So @ehouarn you have it in 1D or just in 3D?

**Comment by ehouarn** [comment]
After some investigations: The values mentioned in the message are powers of pressure, not pressure itself. So this just means that some information is sought at 10**(-3.1)=7.9E-4, outside the predefined pressure grid (which stops at 10**-3).

And there is a mismatch between the top layer pressure in 1D or 3D.
 In 1D we have:
  PRESNIVS
   294147.240516825        278690.364708110        254015.274914879     
...
  0.279683499458116       0.220006832954346       0.173063504426904     
  0.136136574316017     

Whereas in 3D:
000:  PRESNIVS(           1 )=   294147.240000000        Z ~   0.985100817881494     
...
000:  PRESNIVS(          62 )=  0.220006830000000        Z ~    706.281722064773     
000:  PRESNIVS(          63 )=  0.173063505000000        Z ~    718.281721227778     
000:  PRESNIVS(          64 )=  7.619749500000000E-002   Z ~    759.298222224199

**Comment by aymeric-spiga** [comment]
So this is only the latest level that is different. I think in 3D fully coupled with the dynamical core the latest vertical level should be closest as possible to zero

**Comment by aymeric-spiga** [comment]
For what it's worth, the problem disappears (no warning) when running the model in `makestart` with 61 levels instead of 64 levels (removing the 3 uppermost levels). Also the model is running MUCH faster. Looks like the warning does not make the model crash, but slows it down.

**Comment by aymeric-spiga** [comment]
I added a new branch https://github.com/aymeric-spiga/dynamico-giant/tree/work_61levels to share my configuration.

**Comment by aymeric-spiga** [comment]
The problem was that at 64 levels, a level in DYNAMICO is higher than the uppermost limit of the correlated-k database (here $10^-3$~Pa), hence the warning. It is not seen in 1D calculations because the way the last level is treated differs between DYNAMICO and LMDZ: DYNAMICO has a higher boundary that is always at p=0 to ensure conservation. Using 61 levels solves the problem, but resetting vertical levels in `z2sig.def` could have done the job as well. Or recomputing correlated-k grid, but here we do not necessarily need to go higher than $10^-3$~Pa
